// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SliderController from "./slider_controller"
import ProductVariantController from "./product_variant_controller"
import VisibilityController from "./visibility_controller"
import ProductController from "./product_controller"

application.register("slider", SliderController)
application.register("product-variant", ProductVariantController)
application.register("visibility", VisibilityController)
application.register("product", ProductController)


import DashboardSidebarController from "./dashboard_sidebar_controller"
import DashboardFlashController from "./dashboard_flash_controller"
import DashboardDynamicKVFormController from "./dashboard_dynamic_kv_form_controller"
import DashboardImageUploadController from "./dashboard_image_upload_controller"
application.register("dashboard-sidebar", DashboardSidebarController)
application.register("dashboard-flash", DashboardFlashController)
application.register("dashboard-dynamic-kv-form", DashboardDynamicKVFormController)
application.register("dashboard-image-upload", DashboardImageUploadController)