version: "3.9"

services:
  postgres:
    container_name: hassmac-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=250"]
    ports:
      - "6543:5432"

volumes:
  postgres_data: { }