test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

scaleway:
  service: S3
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_ACCESS_KEY') %>
  endpoint: https://s3.fr-par.scw.cloud
  region: fr-par
  bucket: hassmacdev

cloudflare:
  service: S3
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_ACCESS_KEY') %>
  endpoint: https://d2171d82d657ea129976e35f40426832.r2.cloudflarestorage.com
  region: auto
  bucket: images

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
#scaleway_dev:
#  service: S3
#  access_key_id: <%#= Rails.application.credentials.dig(:aws, :access_key_id) %>
#  secret_access_key: <%#= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#  region: PAR
#  bucket: https://hassmac-dev.s3.fr-par.scw.cloud

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
