development: &default
  secret: <%= ENV.fetch('STRIPE_SECRET', "") %>
  webhook_signing: <%= ENV.fetch('STRIPE_WEBHOOK_SIGNING', "") %>
  url: https://dashboard.stripe.com/test

production:
  <<: *default
  url: https://dashboard.stripe.com
