name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  SERVER_IMAGE: ghcr.io/${{ github.repository }}/server-rails
  CLIENT_IMAGE: ghcr.io/${{ github.repository }}/client

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # This permissions block explicitly grants the workflow specific access rights
    permissions:
      contents: read  # Permission to checkout/read repository code
      packages: write  # Permission to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for server-rails image
        id: meta-server
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.SERVER_IMAGE }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push server-rails image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}

      - name: Extract metadata for client image
        id: meta-client
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.CLIENT_IMAGE }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          build-args: |
            PUBLIC_ENV__FRONT_URL=https://assmac.com
            PUBLIC_ENV__SRV_URL=https://srv.assmac.com

      - name: Output image information
        run: |
          echo "::set-output name=server_image::${{ env.SERVER_IMAGE }}:latest"
          echo "::set-output name=client_image::${{ env.CLIENT_IMAGE }}:latest"
          
          echo "================================================================"
          echo "Build completed successfully!"
          echo "================================================================"
          echo "Pull the server-rails image with:"
          echo "docker pull ${{ env.SERVER_IMAGE }}:latest"
          echo ""
          echo "Pull the client image with:"
          echo "docker pull ${{ env.CLIENT_IMAGE }}:latest"
          echo "================================================================"
